config/routes.rb
Rails.application.routes.draw do

  
  get 'sessions/new'

  root 'static_pages#home'
  get 'home' => 'static_pages#home'
  get 'help' => 'static_pages#help'
  get 'about' => 'static_pages#about'
  get 'signup' => 'users#new'
  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'

  resources :users

   

  end
  

app/models/user.rb
class User < ActiveRecord::Base
    attr_accessor :remember_token
    before_save {self.email = email.downcase}
    validates :name, presence: true, length: {maximum: 50}
    validates :email, presence: true, length: {maximum: 50}, uniqueness: { case_sensitive: false }
    has_secure_password
    validates :password, length: {minimum: 3}

    def User.digest(string)
        cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST : BCrypt::Engine.cost
        BCrypt::Password.create(string, cost: cost)
    end
    
    # This creates one token per user.
    def User.new_token
        SecureRandom.urlsafe_base64
    end 

    def remember        
        self.remember_token = User.new_token
        update_attribute(:remember_digest, User.digest(remember_token))
    end
    
    # remember digest is set when remember is called.
    # model is able to access its attributes by just using the variable name
    def authenticated?(remember_token)
        return false if remember_digest.nil?
        BCrypt::Password.new(remember_digest).is_password?(remember_token)
    end
    
    def forget
        update_attribute(:remember_digest, nil)
    end
    


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper

  def hello
  end

  # Putting this line  (before_filter :authorize) inside a certain controller will force the user to login 
  
  def authorize
    redirect_to '/login' unless current_user
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new

  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      flash.now[:success] = "You are not logged in"
      log_in user #this is from the session helper method 
      params[:session][:remember_me] == "1" ? remember(user) : forget(user)
      redirect_to user
    else
      flash.now[:danger] = "Invalid email/password combination"
      render 'new'
    end
  end
  
  def destroy
    flash.now[:success] = "You have succesfully logged out"
    log_out
    redirect_to root_path
  end


end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  

 before_action :logged_in_user, only: [:edit, :update, :destroy]
 before_action :correct_user, only: [:edit, :update]

  def index
    @users = User.all
  end 
  
  def show
    @user = User.find(params[:id])  
  end 
  
  def new
    @user = User.new
  end

  def edit
    @user = User.find(params[:id])
  end 

  def create
    @user = User.new(user_params)
    if(@user.save)
      log_in @user
      flash[:success] = "Welcome to the Sample App!"
      redirect_to @user
    else
      render 'new'
    end
  end
  
  def destroy
    user = User.find(params[:id])
    if(user.destroy)
      flash[:success] = "Successfully Deleted User"
    end 
      redirect_to users_url
  end 

  def update
    user = User.find(params[:id])
    if(user.update_attributes(user_params))
      flash[:success] = "Successfully Updated User"
    end
      redirect_to user_url
  end 
  
  def logged_in_user
      unless logged_in?
        flash[:danger] = "Please log in"
        redirect_to login_url
      end
      
  end
  
  def correct_user
    @user = User.find(params[:id])
    redirect_to(users_url) unless @user == current_user
  end 
  
  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
  
  
end
 

app/helpers/application_helper.rb
module ApplicationHelper


    def full_title(page_title = '')
        base_title = "Ruby on Rails Tutorial Sample App"
        if page_title.empty?
            base_title
        else
        "#{page_title} | #{base_title}"
        end
    end

    ## grab avatar information of the user
    def gravatar_for(user)
        gravatar_id = Digest::MD5::hexdigest(user.email.downcase);
        gravatar_url = "https://secure.gravatar.com/avatar/{#gravatar_id}"
        image_tag(gravatar_url, alt: user.name, class: "gravatar")
    end 
    
    def adminornot?
        if (current_user.admin?)
            "ADMIN - #{current_user.name}"
        else
            "#{current_user.name}"
        end
    end
    

    

end

app/helpers/ls_helper.rb
module LsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

    def log_in(user)
        session[:user_id] = user.id
    end

    def remember(user)
        user.remember
        cookies.permanent.signed[:user_id] = user.id
        cookies.permanent[:remember_token] = user.remember_token
    end
    
    
    def current_user
        if( user_id = session[:user_id])
            @current_user ||= User.find_by(id: user_id)
        elsif (user_id = cookies.signed[:user_id])
            user = User.find_by(id: user_id)
            if user && user.authenticated?(cookies[:remember_token])
                log_in user
                @current_user = user
            end
        end
    end

    def logged_in?
        !current_user.nil?
    end

    def forget(user)
        user.forget
        cookies.delete(:user_id)
        cookies.delete(:remember_token)
    end
    

    def log_out
        forget(current_user)
        session.delete(:user_id)
        @current_user = nil
    end
    

    
    
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_footer.html.erb
<footer class="well">

    <h3> <strong> Footer Partial </strong> </h3>

</footer>

app/views/layouts/_nav.html.erb
<nav class="well row">
    <h3> <strong> Navigation Partial </strong> </h3>
    <ul class="col-sm-4">
        <li> <%= link_to 'Home', root_path %> </li>
        <li> <%= link_to 'About', about_path %> </li>
        <li> <%= link_to 'Help', help_path %> </li>
    </ul>

    <ul class="col-sm-4">
        <li><%= link_to 'Users', users_path %></li>
        <% if logged_in? %>
            <li> <%= adminornot? %> <%= link_to 'Log out', logout_path, method: :delete %> </li>
        <% else %>
        <li><%= link_to 'Login', login_path %></li>
        <li><%= link_to 'Sign Up', new_user_path %> </li>
        <% end %>
    </ul>


</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title> <%= full_title(yield(:title)) %> </title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="container">

<%= render 'layouts/nav' %>


<% flash.each do |message_type, message| %>
  <div class="alert alert-<%= message_type %>"> <%= message %> </div>
<% end %>

<%= yield %>

<%= debug(params) if Rails.env.development? %>

<%= render 'layouts/footer' %>

</div>
</body>
</html>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>

    <div id="error_explanation">
            <div class="alert alert-danger">
                The form contains <%= pluralize(@user.errors.count, "error") %>
            </div>

            <ul>
                <% @user.errors.full_messages.each do |msg| %>
                    <li> <%= msg %> </li>
                <% end %>
            </ul>
    </div>

<% end %>

app/views/shared/_user.html.erb
<!-- We use partial to render each user div -->

    <aside class="col-md-6">
        <section class="user_info">
            <h1>
            <%= gravatar_for user %>
             <%= link_to user.name, user %> <br>
            <p> <small> <%= user.email %> </small> </p>
            </h1>

             <!-- why don't we show this iff the current user is logged in -->
             <% if logged_in? && current_user.id == user.id %>
                <%= link_to "Edit", edit_user_path(user), class: "btn btn-success" %>
             <% end %>
             <% if logged_in? && current_user.admin? %>
                 <%= link_to "Delete", user, method: :delete, data: { confirm: "you sure?"}, class: "btn btn-danger" %>
             <% end %>

        </section>
    </aside>

app/views/static_pages/about.html.erb
<h1>StaticPages#about</h1>
<p>Find me in app/views/static_pages/about.html.erb</p>

app/views/static_pages/help.html.erb
<h1>StaticPages#help</h1>
<p>Find me in app/views/static_pages/help.html.erb</p>

app/views/static_pages/home.html.erb
<% provide(:title, "Home") %>
<h1>StaticPages#Home</h1>
<p>Find me in app/views/static_pages/home.html.erb</p>

app/views/users/edit.html.erb
<%= form_for(@user) do |f| %>
    
    <%= f.label :name %>
    <%= f.text_field :name, class: "form-control" %>

    <%= f.label :email %>
    <%= f.email_field :email, class: "form-control" %>

    <%= f.submit "Submit", class: "btn btn-default" %>
    
<% end %>

app/views/users/index.html.erb
<div class="container"> 
    
    <%= render partial: 'shared/user', collection: @users %>

</div>

app/views/users/new.html.erb
<% provide(:title, "Sign up") %>

<div class="row">

    <div class="col-md-6 col-md-offset-3 form">

    <h1 class="text-center"> Sign Up </h1>

    <%= form_for(@user) do |f| %>

       <!-- <%= render 'shared/error_messages' %> -->

        <%= f.label :name %>
        <%= f.text_field :name, class: 'form-control'%>

        <%= f.label :email %>
        <%= f.email_field :email, class: 'form-control' %>

        <%= f.label :password %>
        <%= f.password_field :password, class: 'form-control' %>

        <%= f.label :password_confirmation, "Confirmation" %>
        <%= f.password_field :password_confirmation, class: 'form-control' %>

        <%= f.submit "Create my account", class: "btn btn-primary" %>

    <% end %>


    </div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>

<%= render 'shared/user', user: @user %>